name: football_quiz
version: 6.1.2+3
publish_to: none
description: A Football Quiz App
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  avatar_glow: 3.0.1
  font_awesome_flutter: 10.7.0
  confirm_dialog: 1.0.3
  art_sweetalert: 0.0.5
  timer_count_down: 2.2.2
  get_storage: 2.1.1
  contained_tab_bar_view: 0.8.0
  convex_bottom_bar: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

